# Project information
site_name: Craftsman
site_description: Advanced command line interface for Codeigniter 3.0 using the Symfony Console component.
site_author: David Sosa Valdes
site_url: https://ci-craftsman.github.io/documentation/

# Repository
repo_name: Craftsman
repo_url: https://github.com/CI-Craftsman/CLI

# Copyright
copyright: |
  <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/80x15.png" /></a> Craftsman is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC SA License</a>.

theme: material

# Options
extra:
  logo: 'images/ic_cr.png'
  palette:
    primary: 'teal'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  social:
    - type: 'github'
      link: 'https://github.com/davidsosavaldes'
    - type: 'twitter'
      link: 'https://twitter.com/itsdsv'
    - type: 'linkedin'
      link: 'https://mx.linkedin.com/in/david-sosa-valdes'

# Page tree
pages:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Commands: commands.md
  - Resources: extra.md
  - Contributions: contributions.md

# Extensions
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - footnotes
  - meta
  - toc(permalink=true)
