site_name: 'Craftsman'
site_description: 'A short description of my project'
site_author: 'David Sosa Valdes'
site_url: 'https://github.com/CI-Craftsman/CLI'

repo_name: 'CLI'
repo_url: 'https://github.com/CI-Craftsman/CLI'

copyright: 'Copyright (c) 2016 David Sosa Valdes'

pages:
    - Home: index.md
    - Installation: installation.md
    - Usage: usage.md
    - Commands: commands.md
    - Extra: extra.md
theme: material
extra:
  version: '4.1.0'
  palette:
    primary: 'red'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  author:
    github: 'davidsosavaldes'
    twitter: 'itsdsv'
markdown_extensions:
  - codehilite(css_class=code)
  - admonition
