# Project information
site_name: Craftsman
site_description: Advanced command line interface for Codeigniter 3.0 using the Symfony Console component.
site_author: David Sosa Valdes
site_url: https://ci-craftsman.github.io/documentation/

# Repository
repo_name: GitHub
repo_url: https://github.com/CI-Craftsman/CLI

# Copyright
copyright: Copyright (c) 2016 David Sosa Valdes

# Documentation and theme
theme_dir: material

# Options
extra:
  version: 4.1.0
  github:
    download_release: true
  author:
    github: davidsosavaldes
    twitter: itsdsv

# Extensions
markdown_extensions:
  - codehilite(css_class=code)
  - admonition
  - toc:
      permalink: '#'

# Page tree
pages:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Commands: commands.md
  - Extra: extra.md
